[versions]
coil-compose = "2.4.0"
com-android-plugin = "8.1.0"
compose = "1.4.3"
firebase-bom = "32.2.0"
hilt = "2.47"
hilt-navigation-compose = "1.0.0"
javax-inject = "1"
kotlinx-coroutines = "1.7.3"
material3 = "1.1.1"
monitor = "1.6.1"
navigation-compose = "2.6.0"
org-jetbrains-kotlin-android = "1.9.0"
core-ktx = "1.10.1"
junit = "5.10.0"
lifecycle-runtime-ktx = "2.6.1"
activity-compose = "1.7.2"
ksp = "1.9.0-1.0.12"
moshi = "1.15.0"
okhttp = "4.11.0"
retrofit = "2.9.0"
mockk = "1.13.5"
room-runtime = "2.5.2"
sqlite = "2.3.1"
startup-runtime = "1.1.1"
timber = "5.0.1"
kotlin-compose-compiler-extension = "1.5.1"
android-sdk-target = "33"
android-min-sdk = "28"


[libraries]
androidx-activity = { module = "androidx.activity:activity", version.ref = "activity-compose" }
androidx-core = { module = "androidx.core:core", version.ref = "core-ktx" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
androidx-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle-runtime-ktx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-runtime-ktx" }
androidx-monitor = { module = "androidx.test:monitor", version.ref = "monitor" }
androidx-navigation-common = { module = "androidx.navigation:navigation-common", version.ref = "navigation-compose" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-navigation-runtime = { module = "androidx.navigation:navigation-runtime", version.ref = "navigation-compose" }
androidx-room-common = { module = "androidx.room:room-common", version.ref = "room-runtime" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room-runtime" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room-runtime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room-runtime" }
androidx-sqlite = { module = "androidx.sqlite:sqlite", version.ref = "sqlite" }
androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startup-runtime" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
androidx-ui-unit = { module = "androidx.compose.ui:ui-unit", version.ref = "compose" }
androidx-ui-text = { module = "androidx.compose.ui:ui-text", version.ref = "compose" }
androidx-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
dagger = { module = "com.google.dagger:dagger", version.ref = "hilt" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "hilt" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
javax-inject = { module = "javax.inject:javax.inject", version.ref = "javax-inject" }
hilt-core = { module = "com.google.dagger:hilt-core", version.ref = "hilt" }
junit-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
mockk-dsl = { module = "io.mockk:mockk-dsl", version.ref = "mockk" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "compose" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
moshi-kotlin-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }
moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "okhttp" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
androidx-material = { group = "androidx.compose.material", name = "material", version.ref = "compose" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "com-android-plugin" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }
com-android-library = { id = "com.android.library", version.ref = "com-android-plugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
gradle-versions = { id = "com.github.ben-manes.versions", version = "0.47.0" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.0" }
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version = "1.20.0" }
com-google-gms-google-services = { id = "com.google.gms.google-services", version = "4.3.15" }
firebase-crashlytics-gradle = { id = "com.google.firebase.crashlytics", version = "2.9.7" }
com-google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
org_jetbrains_kotlinx_kover = { id = "org.jetbrains.kotlinx.kover", version = "0.7.2" }
com_osacky_doctor = { id = "com.osacky.doctor", version = "0.8.1" }
[bundles]

