[versions]
annotation = "1.7.1"
coil-compose = "2.5.0"
com-android-plugin = "8.2.1"
compose = "1.5.4"
cronet = "113.5672.61"
firebase-perf = "20.5.1"
play-services-cronet = "18.0.1"
firebase-bom = "32.7.0"
hilt = "2.50"
hilt-navigation-compose = "1.1.0"
javax-inject = "1"
kotlinx-coroutines = "1.7.3"
material3 = "1.1.2"
monitor = "1.6.1"
navigation-compose = "2.7.6"
kotlin = "1.9.21"
core-ktx = "1.12.0"
junit = "5.10.1"
lifecycle-runtime-ktx = "2.7.0"
activity-compose = "1.8.2"
ksp = "1.9.20-1.0.14"
moshi = "1.15.0"
okhttp = "4.12.0"
retrofit = "2.9.0"
mockk = "1.13.9"
room = "2.6.1"
sqlite = "2.4.0"
startup-runtime = "1.1.1"
timber = "5.0.1"
kotlin-compose-compiler-extension = "1.5.4"
android-sdk-target = "34"
android-min-sdk = "28"


[libraries]
androidx-activity = { module = "androidx.activity:activity", version.ref = "activity-compose" }
androidx-animation-android = { module = "androidx.compose.animation:animation-android", version.ref = "compose" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-core = { module = "androidx.core:core", version.ref = "core-ktx" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-foundation-layout-android = { module = "androidx.compose.foundation:foundation-layout-android", version.ref = "compose" }
androidx-foundation-android = { module = "androidx.compose.foundation:foundation-android", version.ref = "compose" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
androidx-material-android = { module = "androidx.compose.material:material-android", version.ref = "compose" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle-runtime-ktx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-runtime-ktx" }
androidx-monitor = { module = "androidx.test:monitor", version.ref = "monitor" }
androidx-navigation-common = { module = "androidx.navigation:navigation-common", version.ref = "navigation-compose" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-navigation-runtime = { module = "androidx.navigation:navigation-runtime", version.ref = "navigation-compose" }
androidx-room-common = { module = "androidx.room:room-common", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-runtime-android = { module = "androidx.compose.runtime:runtime-android", version.ref = "compose" }
androidx-sqlite = { module = "androidx.sqlite:sqlite", version.ref = "sqlite" }
androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "startup-runtime" }
androidx-ui-android = { module = "androidx.compose.ui:ui-android", version.ref = "compose" }
androidx-ui-graphics-android = { module = "androidx.compose.ui:ui-graphics-android", version.ref = "compose" }
androidx-ui-text-android = { module = "androidx.compose.ui:ui-text-android", version.ref = "compose" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
androidx-ui-unit-android = { module = "androidx.compose.ui:ui-unit-android", version.ref = "compose" }
androidx-ui-tooling-preview-android = { module = "androidx.compose.ui:ui-tooling-preview-android", version.ref = "compose" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
dagger = { module = "com.google.dagger:dagger", version.ref = "hilt" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "hilt" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-perf = { module = "com.google.firebase:firebase-perf", version.ref = "firebase-perf" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
javax-inject = { module = "javax.inject:javax.inject", version.ref = "javax-inject" }
hilt-core = { module = "com.google.dagger:hilt-core", version.ref = "hilt" }
junit-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
mockk-dsl = { module = "io.mockk:mockk-dsl", version.ref = "mockk" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
moshi-kotlin-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }
moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "okhttp" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
cronet-api = { module = "org.chromium.net:cronet-api", version.ref = "cronet" }
cronet-embedded = { module = "org.chromium.net:cronet-embedded", version.ref = "cronet" }
cronet-okhttp = { group = "com.google.net.cronet", name = "cronet-okhttp", version = "0.1.0" }
play-services-cronet = { module = "com.google.android.gms:play-services-cronet", version.ref = "play-services-cronet" }
[plugins]
com-android-application = { id = "com.android.application", version.ref = "com-android-plugin" }
com-android-library = { id = "com.android.library", version.ref = "com-android-plugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
gradle-versions = { id = "com.github.ben-manes.versions", version = "0.50.0" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.4" }
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version = "1.28.0" }
com-google-gms-google-services = { id = "com.google.gms.google-services", version = "4.4.0" }
firebase-crashlytics-gradle = { id = "com.google.firebase.crashlytics", version = "2.9.9" }
firebase-perf-gradle = { id = "com.google.firebase.firebase-perf", version = "1.4.2" }
com-google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
org_jetbrains_kotlinx_kover = { id = "org.jetbrains.kotlinx.kover", version = "0.7.5" }
com_osacky_doctor = { id = "com.osacky.doctor", version = "0.9.1" }
org-jlleitschuh-gradle-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "12.1.0" }
org-gradle-android-cache-fix = { id = "org.gradle.android.cache-fix", version = "3.0" }
androidx-room = { id = "androidx.room", version.ref = "room" }
[bundles]

