name: Build release app

on:
  push:
    branches: [ "main" ]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          gradle-home-cache-cleanup: true

      # Build debug app to improve pr check build speed by storing debug cache
      - name: Build debug and release apk
        run: ./gradlew app:assemble

      - name: Run detket plugin
        run: ./gradlew detektAll

      - name: Run unit test
        run: ./gradlew testDebugUnitTest

      - name: Run dependency analysis android gradle plugin
        run: ./gradlew buildHealth
