name: Run PR checks using debug build

on:
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build apk
        run: ./gradlew app:assembleDebug

      - name: Run detket plugin
        run: ./gradlew detektAll

      - name: Run dependency analysis android gradle plugin
        run: ./gradlew buildHealth

      - name: Run Coverage
        run: ./gradlew app:allDebugCoverage

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/allDebugCoverage/allDebugCoverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
